language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "Fruit-Shopper-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: fruit-shopper # see README
  api_key:
    secure: "bPEvTvspdSwAV9pYTK2Ek2Ptbo6lz+P3nUBZDZLFJyCPkrayYp70iVhWa9bj6jepvHbKhuzrbNjSbYK/SXQk2iHXgTf5Q9cyn65d22WZXLqAW/Pl6b8Os2QIEIkTSrGG9ncTIYy5UaRbA3aE3+BHRsCEJBgHwOOoDfHVa705mnS5S3ezcEmcHWyauGbDqdKNPuowD1oEkrvRCD5RgozuPqPIDn71TrjBx4Urpu/oo57AdAqfxyBHeG9pEh0OG1BoW+JXqV+bZNWYQ+y/3xkfglpwfoyssEFPaNTdXN2AySS5uki0L6kkSwR2FqmwxpSOd0kcEbWEl37RGqW061Hv7whhmVT3B+zEYLjee8XkbLkDkmqgycPcOzQU+Ji3gvB3YhnFLEnlMjn1flw1j1zXL+Cl/IlAhqC+o2es0IY2rENd2fVBvjyb1B86Ndvkb45mhA+SnxXSsvjenQjB/GlLO7nLk9UEdcY+WrMV94br8P92NlpVrTN3NbtcKWqgK1b2RnhbGlUzBapVyWyv8qnSlm5ftCJX6St695zq91xMFvVDqovvm31n1PASJOBbg57zG0RUXgQK/GagoPWHcWkcyCcUIL6MYEYvohqmVkCkZfPKciHlNAsJX3AR0dJzlcxIYFmp+HZwWDC8/5QEx84KW/m4P5tFdJeNbiDiP0afvlE"= # see README
